require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@4.6.2_@capacitor+core@4.6.2/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@4.6.2_@capacitor+core@4.6.2/node_modules/@capacitor/ios'
  pod 'CapacitorCommunityBarcodeScanner', :path => '../../node_modules/.pnpm/@capacitor-community+barcode-scanner@3.0.1_@capacitor+core@4.6.2/node_modules/@capacitor-community/barcode-scanner'
  pod 'CapacitorCommunitySqlite', :path => '../../node_modules/.pnpm/@capacitor-community+sqlite@4.6.1-2_@capacitor+core@4.6.2/node_modules/@capacitor-community/sqlite'
  pod 'CapacitorDialog', :path => '../../node_modules/.pnpm/@capacitor+dialog@4.1.0_@capacitor+core@4.6.2/node_modules/@capacitor/dialog'
  pod 'CapacitorHaptics', :path => '../../node_modules/.pnpm/@capacitor+haptics@4.1.0_@capacitor+core@4.6.2/node_modules/@capacitor/haptics'
  pod 'CapacitorToast', :path => '../../node_modules/.pnpm/@capacitor+toast@4.1.0_@capacitor+core@4.6.2/node_modules/@capacitor/toast'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
